version: 3
tasks:
  setup:
    cmds:
      - gem install --user jekyll bundler
      - bundler install
  build:
    desc: build data
    aliases: ['b']
    cmds:
      - bundle exec jekyll b

  server:
    desc: server locally
    aliases: ['s']
    cmds:
      - bundle exec jekyll s

  run:
    desc: run jekyll with passed flags
    aliases: ['r']
    cmds:
      - bundle exec jekyll {{.CLI_ARGS}}
